# Generated by Django 4.1.2 on 2022-10-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iou',
            name='expiration',
            field=models.DateTimeField(),
        ),
    ]
