# Generated by Django 4.1.2 on 2022-10-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
